# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crit_GK_exact_1D <- function(xi, H) {
    .Call(`_PCOtesthmin_crit_GK_exact_1D`, xi, H)
}

crit_EK_exact_1D <- function(xi, H) {
    .Call(`_PCOtesthmin_crit_EK_exact_1D`, xi, H)
}

crit_BK_exact_1D <- function(xi, H) {
    .Call(`_PCOtesthmin_crit_BK_exact_1D`, xi, H)
}

crit_GK_exact_mD_diag <- function(x_i, H, hmin) {
    .Call(`_PCOtesthmin_crit_GK_exact_mD_diag`, x_i, H, hmin)
}

crit_GK_exact_mD_full <- function(x_i, H, hmin) {
    .Call(`_PCOtesthmin_crit_GK_exact_mD_full`, x_i, H, hmin)
}

risque_Lp <- function(p, f, o_i, x, hopt_c, a, b) {
    .Call(`_PCOtesthmin_risque_Lp`, p, f, o_i, x, hopt_c, a, b)
}

risque_Lp_mD_3 <- function(p, f, o_i, nQMC, h, a, b) {
    .Call(`_PCOtesthmin_risque_Lp_mD_3`, p, f, o_i, nQMC, h, a, b)
}

rcpp_hello_world <- function() {
    .Call(`_PCOtesthmin_rcpp_hello_world`)
}

